[tox]
envlist =
    py312
    py312-cov
isolated_build = true

[testenv]
usedevelop = True
description = Run tests
deps =
    pytest
    numpy
    pandas
commands =
    pytest tests -v

[testenv:py312-cov]
usedevelop = True
description = Test with coverage reporting
deps =
    pytest
    pytest-cov
    numpy
    pandas
commands =
    pytest tests --cov=glyphx --cov-report=term-missing --cov-fail-under=50

[pytest]
minversion = 7
testpaths =
    tests
filterwarnings =
    ignore::DeprecationWarning

[coverage:run]
source = glyphx
omit =
    */glyphx/examples/*
    */glyphx/docs/*
    */tests/*

[coverage:report]
exclude_lines =
    pragma: no cover
    except ImportError
    raise AssertionError
    raise NotImplementedError
    def main\(.*\):
    pragma: py{ignore_python_version}
